### ISSUE TITLE
Setup Github Action to run e2e test with Cypress

### ISSUE THREAD

**Issue by carlosazaustre** [PintaApis/developars-club#12]
### Resumen del problema:
No consigo hacer correr de forma correcta los test de cypress en el entorno CI con GitHub Actions.

Este es el último fichero de configuración que he probado:
```yml
name: E2E Tests

on: [push, pull_request]

jobs:
  cypress-run:
    name: e2e testing with Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run dev
      - name: Build web app
        run: npm run build

```

Saltaba el siguiente error. Si está ejecutando `npx cypress` desde el directorio raíz dice que no existe el fichero `cypress.config.js`. Pero si cambio el *working directory* a `apps/web` dice que no encuentra el fichero `package-lock.json`

```
Run cypress-io/github-action@v4
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/work/developars-club/developars-club/apps/web/package-lock.json'
```

Aunque en las últimas acciones lanzadas, se cuelga en el paso `Cypress Run` como se puede ver en #11 

  
#### Comportamiento esperado:

Configurar una GitHub Action que lance los tests e2e por terminal para comprobar que no existen errores.

La complejidad viene quizá por estar usando turborepo.
  
#### Más información :
Para lanzar los tests *end-to-end* de la app, tienes dos formas. Si los quieres  lanzar en modo gráfico, ejecuta:

```
npm run test:e2e:open
```

Si los quieres lanzar en modo consola, ejecuta:

```
npm run test:e2e
```

> Recuerda tener abierta la aplicación en otra terminal con `npm run dev` para que los tests puedan ejecutarse.
